name: ridexpressdriver
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  camera: ^0.11.2
  country_code_picker: ^3.3.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: ^9.2.4
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.3
  google_nav_bar: ^5.0.7
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  lottie: ^3.3.1
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
